//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSTAL_MIX_SQL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class MainPageContent
    {
        public int IdPK { get; set; }
        [Display(Name = "Opis elementu: ")]
        public string opis { get; set; }
        [Display(Name = "Adres URL elementu: ")]
        public string urlAdres { get; set; }
        [Display(Name = "Pozycja na stronie elementu: ")]
        public string pozycja { get; set; }
    }
}
